-- q91. what are the overall business kpis?

select
count(distinct o.order_id) as total_orders,
count(distinct o.customer_id) as active_customers,
count(distinct oi.product_id) as products_sold,
sum(oi.quantity) as units_sold,
round(sum(oi.sales_amount), 2) as total_revenue,
round(sum(oi.profit_amount), 2) as total_profit,
round(
sum(oi.profit_amount) / sum(oi.sales_amount) * 100,
2
) as profit_margin
from orders o
join order_items oi
on o.order_id = oi.order_id
where o.order_status != 'cancelled';

-- q92. which categories are the strongest overall?

select
p.category,
round(sum(oi.sales_amount), 2) as revenue,
round(sum(oi.profit_amount), 2) as profit,
round(
sum(oi.profit_amount) / sum(oi.sales_amount) * 100,
2
) as profit_margin,
sum(oi.quantity) as units_sold
from products p
join order_items oi
on p.product_id = oi.product_id
join orders o
on oi.order_id = o.order_id
where o.order_status != 'cancelled'
group by p.category
order by profit desc;

-- q93. which products are high-revenue but low-margin?

select
p.product_id,
p.product_name,
p.category,
round(sum(oi.sales_amount), 2) as revenue,
round(sum(oi.profit_amount), 2) as profit,
round(
sum(oi.profit_amount) / sum(oi.sales_amount) * 100,
2
) as profit_margin
from products p
join order_items oi
on p.product_id = oi.product_id
join orders o
on oi.order_id = o.order_id
where o.order_status != 'cancelled'
group by
p.product_id,
p.product_name,
p.category
having
sum(oi.sales_amount) > (
select avg(product_revenue)
from (
select
product_id,
sum(sales_amount) as product_revenue
from order_items
group by product_id
) as product_sales
)
and sum(oi.profit_amount) / sum(oi.sales_amount) < 0.20
order by revenue desc;

-- q94. which categories have strong sales but weak profitability?

select
p.category,
round(sum(oi.sales_amount), 2) as revenue,
round(sum(oi.profit_amount), 2) as profit,
round(
sum(oi.profit_amount) / sum(oi.sales_amount) * 100,
2
) as profit_margin
from products p
join order_items oi
on p.product_id = oi.product_id
join orders o
on oi.order_id = o.order_id
where o.order_status != 'cancelled'
group by p.category
having
sum(oi.sales_amount) >= (
select avg(category_revenue)
from (
select
p2.category,
sum(oi2.sales_amount) as category_revenue
from products p2
join order_items oi2
on p2.product_id = oi2.product_id
join orders o2
on oi2.order_id = o2.order_id
where o2.order_status != 'cancelled'
group by p2.category
) as category_average
)
and sum(oi.profit_amount) / sum(oi.sales_amount) < 0.20
order by revenue desc;

-- q95. how much revenue is generated by each customer segment?

select
c.customer_segment,
count(distinct c.customer_id) as customers,
count(distinct o.order_id) as orders,
round(sum(oi.sales_amount), 2) as revenue,
round(sum(oi.profit_amount), 2) as profit,
round(
sum(oi.profit_amount) / sum(oi.sales_amount) * 100,
2
) as profit_margin
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
where o.order_status != 'cancelled'
group by c.customer_segment
order by revenue desc;

-- q96. how much revenue and profit are lost through returns?

select
count(distinct r.return_id) as total_returns,
round(sum(r.refund_amount), 2) as total_refunds,
round(
sum(r.refund_amount) /
(
select sum(oi.sales_amount)
from order_items oi
join orders o
on oi.order_id = o.order_id
where o.order_status != 'cancelled'
) * 100,
2
) as refund_to_revenue_percentage
from returns r;

-- q97. which categories need attention because of high returns?

select
p.category,
count(distinct r.return_id) as total_returns,
round(sum(r.refund_amount), 2) as refund_amount,
round(
count(distinct r.return_id) * 100.0 /
count(distinct oi.order_item_id),
2
) as return_rate
from products p
join order_items oi
on p.product_id = oi.product_id
join orders o
on oi.order_id = o.order_id
left join returns r
on oi.order_id = r.order_id
and oi.product_id = r.product_id
where o.order_status != 'cancelled'
group by p.category
order by return_rate desc;

-- q98. which regions are performing below the company average?

with regional_sales as (
select
o.shipping_region as region,
sum(oi.sales_amount) as revenue,
sum(oi.profit_amount) as profit
from orders o
join order_items oi
on o.order_id = oi.order_id
where o.order_status != 'cancelled'
group by o.shipping_region
)
select
region,
round(revenue, 2) as revenue,
round(profit, 2) as profit
from regional_sales
where revenue < (
select avg(revenue)
from regional_sales
)
order by revenue asc;

-- q99. which months generate the highest revenue and profit?

select
year(o.order_date) as year,
month(o.order_date) as month_number,
monthname(o.order_date) as month_name,
round(sum(oi.sales_amount), 2) as revenue,
round(sum(oi.profit_amount), 2) as profit,
round(
sum(oi.profit_amount) / sum(oi.sales_amount) * 100,
2
) as profit_margin
from orders o
join order_items oi
on o.order_id = oi.order_id
where o.order_status != 'cancelled'
group by
year(o.order_date),
month(o.order_date),
monthname(o.order_date)
order by revenue desc;

-- q100. create an overall business performance classification

with category_performance as (
select
p.category,
sum(oi.sales_amount) as revenue,
sum(oi.profit_amount) as profit,
sum(oi.quantity) as units_sold
from products p
join order_items oi
on p.product_id = oi.product_id
join orders o
on oi.order_id = o.order_id
where o.order_status != 'cancelled'
group by p.category
),
category_analysis as (
select
category,
revenue,
profit,
units_sold,
profit / revenue * 100 as profit_margin
from category_performance
)
select
category,
round(revenue, 2) as revenue,
round(profit, 2) as profit,
units_sold,
round(profit_margin, 2) as profit_margin,
case
when profit_margin >= 30
and revenue >= (
select avg(revenue)
from category_analysis
)
then 'excellent'

    when profit_margin >= 20
         and revenue >= (
             select avg(revenue)
             from category_analysis
         )
        then 'strong'

    when profit_margin < 20
         and revenue >= (
             select avg(revenue)
             from category_analysis
         )
        then 'high sales - low margin'

    when profit_margin >= 20
         and revenue < (
             select avg(revenue)
             from category_analysis
         )
        then 'growth opportunity'
    else 'needs attention'
end as business_classification

from category_analysis
order by revenue desc;
